- name: Set Hostname
  ansible.builtin.shell: set-hostname frontend

- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Placing Expense Config file in Nginx
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Include App Pre-requisites
  ansible.builtin.import_role:
    name: Common
    tasks-from: app_prereq

- name: Starting Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
